extra:
  alternate:
    - name: English
      link: README.md
      lang: en
    - name: 中文
      link: zh-cn/
      lang: zh
    - name: Español
      link: es/
      lang: es
    - name: Français
      link: fr-fr/
      lang: fr
    - name: עברית
      link: he-il/
      lang: he
    - name: Português
      link: pt-br/
      lang: pt
    - name: Русский
      link: ru-ru/
      lang: ru
    - name: 日本語
      link: ja/
      lang: ja
  version:
    provider: mike
plugins:
  - search:
      lang:
        - en
        - es
        - fr
        - pt
        - ru
        - ja
      prebuild_index: true
      separator: '[\s\-\_]+'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - fenced_code
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      marker: ''
      permalink: true
      toc_depth: 3
  - wikilinks
nav:
  - README.md
site_name: QMK Firmware Docs
site_url: https://docs.qmk.fm
theme:
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  language: en
  name: material
