extra_css:
  - stylesheets/qmk.css
extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: /master/en/
      lang: en
    - name: 日本語
      link: /master/jp/
      lang: jp
    - name: 简体中文
      link: /master/zh/
      lang: zh
plugins:
  - search:
      lang:
        - en
        - ja
      prebuild_index: true
      separator: '[\s\-\_]+'
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - fenced_code
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      marker: ''
      permalink: true
      toc_depth: 3
  - wikilinks
nav:
  - Home: README.md
  - 完全菜鸟指南:
    - Introduction: tutorial.md
    - 入门: newbs_getting_started.md
    - 构建你的第一个固件: newbs_building_firmware.md
    - 刷新固件: newbs_flashing.md
    - 测试和调试: newbs_testing_debugging.md
    - Git最佳实践:
      - 使用你分叉(fork)的主分支(master): newbs_git_using_your_master_branch.md
      - 解决合并冲突: newbs_git_resolving_merge_conflicts.md
      - 重新同步一个分支: newbs_git_resynchronize_a_branch.md
    - 学习资源: newbs_learn_more_resources.md
  - QMK基础:
    - QMK简介: tutorial.md
    - QMK命令行工具: cli.md
    - QMK命令行工具配置: cli_configuration.md
    - 向QMK贡献代码: contributing.md
    - 如何使用GitHub: getting_started_github.md
    - 获得帮助: support.md
  - 非兼容性修改:
    - Overview: breaking_changes.md
    - 我的PR已经被标记为非兼容性修改: breaking_changes_instructions.md
    - 2019年8月30日: ChangeLog/20190830.md
  - 问题与解答:
    - 一般问题: faq_general.md
    - 构建/编译: faq_build.md
    - 调试/故障排除: faq_debug.md
    - 布局: faq_keymap.md
    - Zadig驱动安装: driver_installation_zadig.md
  - 详细指南:
    - 安装构建工具: newbs_getting_started.md
    - vagrant指南: getting_started_vagrant.md
    - 构建/编译指南: getting_started_make_guide.md
    - 刷新固件: flashing.md
    - 定制功能: custom_quantum_functions.md
    - 布局概述: keymap.md
  - 硬件:
    - 兼容的单片机: compatible_microcontrollers.md
    - AVR处理器: hardware_avr.md
    - 驱动: hardware_drivers.md
  - 参考:
    - 键盘指南: hardware_keyboard_guidelines.md
    - 配置选项: config_options.md
    - 键码: keycodes.md
    - 代码书写规范 - C: coding_conventions_c.md
    - 代码书写规范 - Python: coding_conventions_python.md
    - 文档书写规范: documentation_best_practices.md
    - 文档模板: documentation_templates.md
    - 术语表: reference_glossary.md
    - 单元测试: unit_testing.md
    - 实用函数: ref_functions.md
    - 配置器支持: reference_configurator_support.md
    - info.json 格式: reference_info_json.md
    - Python 命令行开发: cli_development.md
  - 特性:
    - 基本键码: keycodes_basic.md
    - US ANSI控制码: keycodes_us_ansi_shifted.md
    - 量子键码: quantum_keycodes.md
    - 高级键码: feature_advanced_keycodes.md
    - 音频: feature_audio.md
    - 自动shift: feature_auto_shift.md
    - 背光: feature_backlight.md
    - 蓝牙: feature_bluetooth.md
    - 热改键: feature_bootmagic.md
    - 组合: feature_combo.md
    - 命令: feature_command.md
    - 消抖 API: feature_debounce_type.md
    - 拨动开关: feature_dip_switch.md
    - 动态宏指令: feature_dynamic_macros.md
    - 编码器: feature_encoders.md
    - 重音号Esc复合键: feature_grave_esc.md
    - 触摸反馈: feature_haptic_feedback.md
    - HD44780 LCD控制器: feature_hd44780.md
    - 自锁键: feature_key_lock.md
    - 布局: feature_layouts.md
    - 前导键: feature_leader_key.md
    - LED阵列: feature_led_matrix.md
    - 宏指令: feature_macros.md
    - 鼠标键: feature_mouse_keys.md
    - OLED驱动: feature_oled_driver.md
    - 一键功能: one_shot_keys.md
    - 指针设备: feature_pointing_device.md
    - PS/2鼠标: feature_ps2_mouse.md
    - RGB灯光: feature_rgblight.md
    - RGB矩阵: feature_rgb_matrix.md
    - 空格候补换挡: feature_space_cadet.md
    - 分体键盘: feature_split_keyboard.md
    - 速录机: feature_stenography.md
    - 换手: feature_swap_hands.md
    - 多击键: feature_tap_dance.md
    - 终端: feature_terminal.md
    - 热敏打印机: feature_thermal_printer.md
    - Unicode: feature_unicode.md
    - 用户空间: feature_userspace.md
    - 速度键: feature_velocikey.md
  - 制造和定制者指南:
    - 手工连线指南: hand_wire.md
    - ISP刷新指南: isp_flashing_guide.md
    - ARM调试指南: arm_debugging.md
    - ADC设备: adc_driver.md
    - I2C设备: i2c_driver.md
    - SPI设备: spi_driver.md
    - WS2812设备: ws2812_driver.md
    - EEPROM设备: eeprom_driver.md
    - GPIO控制: internals_gpio_control.md
    - 自定义键盘矩阵: custom_matrix.md
    - Proton C转换: proton_c_conversion.md
  - 深入了解:
    - 键盘工作原理: how_keyboards_work.md
    - 深入了解QMK: understanding_qmk.md
  - 其他话题:
    - 使用Eclipse开发QMK: other_eclipse.md
    - 使用VSCode开发QMK: other_vscode.md
    - 支持: support.md
    - 翻译QMK文档: translating.md
  - QMK 内构 (正在编写):
    - 定义: internals_defines.md
    - 输入回调寄存器: internals_input_callback_reg.md
    - Midi设备: internals_midi_device.md
    - Midi设备配置过程: internals_midi_device_setup_process.md
    - Midi工具库: internals_midi_util.md
    - 发送函数: internals_send_functions.md
    - Sysex工具: internals_sysex_tools.md
repo_name: qmk/qmk_firmware
repo_url: https://github.com/qmk/qmk_firmware
site_name: QMK Firmware Docs
site_url: https://docs.qmk.fm/master/zh
theme:
  favicon: images/favicon.ico
  features:
    - navigation.expand
    #- navigation.instant
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Varela Round
    code: Source Code Pro
  icon:
    repo: fontawesome/brands/github
  language: zh
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
