extra_css:
  - stylesheets/qmk.css
extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: /master/en/
      lang: en
    - name: 日本語
      link: /master/jp/
      lang: jp
    - name: 简体中文
      link: /master/zh/
      lang: zh
plugins:
  - search:
      lang:
        - en
        - ja
      prebuild_index: true
      separator: '[\s\-\_]+'
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - fenced_code
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      marker: ''
      permalink: true
      toc_depth: 3
  - wikilinks
nav:
  - Home: README.md
  - チュートリアル:
    - 入門: tutorial.md
    - セットアップ: newbs_getting_started.md
    - 初めてのファームウェアの構築: newbs_building_firmware.md
    - ファームウェアのフラッシュ: newbs_flashing.md
    - 手助けを得る/サポート: support.md
    - 他のリソース: newbs_learn_more_resources.md
    - シラバス: syllabus.md
  - FAQ:
    - 一般的な FAQ: faq_general.md
    - QMK のビルド/コンパイル: faq_build.md
    - QMK のデバッグ: faq_debug.md
    - QMK のトラブルシューティング: faq_misc.md
    - キーマップ FAQ: faq_keymap.md
    - 用語: reference_glossary.md
  - Configurator:
    - 概要: newbs_building_firmware_configurator.md
    - ステップ・バイ・ステップ: configurator_step_by_step.md
    - トラブルシューティング: configurator_troubleshooting.md
    - QMK API:
      - 概要: api_overview.md
      - API ドキュメント: api_docs.md
      - キーボードサポート: reference_configurator_support.md
      - デフォルトキーマップの追加: configurator_default_keymaps.md
  - CLI:
      - 概要: cli.md
      - 設定: cli_configuration.md
      - コマンド: cli_commands.md
      - Tab 補完: cli_tab_complete.md
  - QMK を使う:
    - ガイド:
      - 機能のカスタマイズ: custom_quantum_functions.md
      - Zadig を使ったドライバのインストール: driver_installation_zadig.md
      - キーマップの概要: keymap.md
      - 開発環境:
        - Docker のガイド: getting_started_docker.md
        - Vagrant のガイド: getting_started_vagrant.md
      - 書き込み:
        - 書き込み: flashing.md
        - ATmega32A の書き込み (ps2avrgb): flashing_bootloadhid.md
      - IDE:
        - QMK での Eclipse の使用: other_eclipse.md
        - QMK での VSCode の使用: other_vscode.md
      - Git のベストプラクティス:
        - 入門: newbs_git_best_practices.md
        - フォーク: newbs_git_using_your_master_branch.md
        - マージの競合の解決: newbs_git_resolving_merge_conflicts.md
        - ブランチの修正: newbs_git_resynchronize_a_branch.md
      - キーボードを作る:
        - Hand Wiring ガイド: hand_wire.md
        - ISP 書き込みガイド: isp_flashing_guide.md
    - 単純なキーコード:
      - 完全なリスト: keycodes.md
      - 基本的なキーコード: keycodes_basic.md
      - 言語固有のキーコード: reference_keymap_extras.md
      - 修飾キー: feature_advanced_keycodes.md
      - Quantum キーコード: quantum_keycodes.md
    - 高度なキーコード:
      - コマンド: feature_command.md
      - 動的マクロ: feature_dynamic_macros.md
      - グレイブ エスケープ: feature_grave_esc.md
      - リーダーキー: feature_leader_key.md
      - モッドタップ: mod_tap.md
      - マクロ: feature_macros.md
      - マウスキー: feature_mouse_keys.md
      - Space Cadet Shift: feature_space_cadet.md
      - US ANSI シフトキー: keycodes_us_ansi_shifted.md
    - ソフトウェア機能:
      - 自動シフト: feature_auto_shift.md
      - コンボ: feature_combo.md
      - デバウンス API: feature_debounce_type.md
      - キーロック: feature_key_lock.md
      - レイヤー: feature_layers.md
      - ワンショットキー: one_shot_keys.md
      - ポインティング デバイス: feature_pointing_device.md
      - ロー HID: feature_rawhid.md
      - シーケンサー: feature_sequencer.md
      - スワップハンド: feature_swap_hands.md
      - タップダンス: feature_tap_dance.md
      - タップホールド設定: tap_hold.md
      - ターミナル: feature_terminal.md
      - ユニコード: feature_unicode.md
      - ユーザスペース: feature_userspace.md
      - WPM 計算: feature_wpm.md
    - ハードウェア機能:
      - 表示:
        - HD44780 LCD コントローラ: feature_hd44780.md
        - OLED ドライバ: feature_oled_driver.md
      - 電飾:
        - バックライト: feature_backlight.md
        - LED マトリックス: feature_led_matrix.md
        - RGB ライト: feature_rgblight.md
        - RGB マトリックス: feature_rgb_matrix.md
      - オーディオ: feature_audio.md
      - Bluetooth: feature_bluetooth.md
      - ブートマジック: feature_bootmagic.md
      - カスタムマトリックス: custom_matrix.md
      - DIP スイッチ: feature_dip_switch.md
      - エンコーダ: feature_encoders.md
      - 触覚フィードバック: feature_haptic_feedback.md
      - ジョイスティック: feature_joystick.md
      - LED インジケータ: feature_led_indicators.md
      - Proton C 変換: proton_c_conversion.md
      - PS/2 マウス: feature_ps2_mouse.md
      - 分割キーボード: feature_split_keyboard.md
      - 速記: feature_stenography.md
      - 感熱式プリンタ: feature_thermal_printer.md
      - Velocikey: feature_velocikey.md
  - QMK の開発:
    - PR チェックリスト: pr_checklist.md
    - 互換性を破る変更/Breaking changes:
      - 概要: breaking_changes.md
      - プルリクエストにフラグが付けられた: breaking_changes_instructions.md
      - 最近の変更履歴: ChangeLog/20210529.md
      - 過去の互換性を破る変更:
          - 2021 Feb 27, 0.12.0: ChangeLog/20210227.md
          - 2020 Nov 28, 0.11.0: ChangeLog/20201128.md
          - 2020 Aug 29, 0.10.0: ChangeLog/20200829.md
          - 2020 May 30, 0.9.0: ChangeLog/20200530.md
          - 2020 Feb 29, 0.8.0: ChangeLog/20200229.md
          - 2019 Aug 30, 0.7.0: ChangeLog/20190830.md
    - C 開発:
      - ARM デバッグ ガイド: arm_debugging.md
      - AVR プロセッサ: hardware_avr.md
      - コーディング規約: coding_conventions_c.md
      - 互換性のあるマイクロコントローラ: compatible_microcontrollers.md
      - ドライバ:
        - ADC ドライバ: adc_driver.md
        - オーディオドライバ: audio_driver.md
        - I2C ドライバ: i2c_driver.md
        - SPI ドライバ: spi_driver.md
        - WS2812 ドライバ: ws2812_driver.md
        - EEPROM ドライバ: eeprom_driver.md
        - シリアル ドライバ: serial_driver.md
        - UART ドライバ: uart_driver.md
      - GPIO 制御: internals_gpio_control.md
      - キーボード ガイドライン: hardware_keyboard_guidelines.md
    - Python 開発:
      - コーディング規約: coding_conventions_python.md
      - QMK CLI 開発: cli_development.md
    - Configurator 開発:
      - QMK API:
        - 開発環境: api_development_environment.md
        - アーキテクチャの概要: api_development_overview.md
    - ハードウェアプラットフォーム開発:
      - Arm/ChibiOS:
        - MCU の選択: platformdev_selecting_arm_mcu.md
        - 早期初期化: platformdev_chibios_earlyinit.md
    - QMK Reference:
      - QMK への貢献: contributing.md
      - QMK ドキュメントの翻訳: translating.md
      - 設定オプション: config_options.md
      - データ駆動型コンフィギュレーション: data_driven_config.md
      - Make ドキュメント: getting_started_make_guide.md
      - ドキュメント ベストプラクティス: documentation_best_practices.md
      - ドキュメント テンプレート: documentation_templates.md
      - コミュニティレイアウト: feature_layouts.md
      - ユニットテスト: unit_testing.md
      - 便利な関数: ref_functions.md
      - info.json 形式: reference_info_json.md
    - より深く知るために:
      - キーボードがどのように動作するか: how_keyboards_work.md
      - マトリックスがどのように動作するか: how_a_matrix_works.md
      - QMK を理解する: understanding_qmk.md
    - QMK の内部詳細(作成中):
      - 定義: internals_defines.md
      - 入力コールバック登録: internals_input_callback_reg.md
      - Midi デバイス: internals_midi_device.md
      - Midi デバイスのセットアップ手順: internals_midi_device_setup_process.md
      - Midi ユーティリティ: internals_midi_util.md
      - Midi 送信関数: internals_send_functions.md
      - Sysex Tools: internals_sysex_tools.md
repo_name: qmk/qmk_firmware
repo_url: https://github.com/qmk/qmk_firmware
site_name: QMK Firmware Docs
site_url: https://docs.qmk.fm/master/ja
theme:
  favicon: images/favicon.ico
  features:
    - navigation.expand
    #- navigation.instant
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Varela Round
    code: Source Code Pro
  icon:
    repo: fontawesome/brands/github
  language: ja
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
