extra_css:
  - stylesheets/qmk.css
extra:
  version:
    provider: mike
plugins:
  - search:
      lang:
        - en
        - ja
      prebuild_index: true
      separator: '[\s\-\_]+'
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - fenced_code
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      marker: ''
      permalink: true
      toc_depth: 3
  - wikilinks
repo_name: qmk/qmk_firmware
repo_url: https://github.com/qmk/qmk_firmware
site_name: QMK Firmware Docs
theme:
  favicon: images/favicon.ico
  features:
    - navigation.expand
    #- navigation.instant
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Varela Round
    code: Source Code Pro
  icon:
    repo: fontawesome/brands/github
  language: en
  logo : images/logo.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
